name: Release

on:
  push:
    tags: ["v*"]
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
